### ISSUE TITLE
Finalize the main website

### ISSUE THREAD

**Issue by reinhapa** [rtcTo/website#2]
Part of how to learn migrate to git and JIRA is still missing and needs a initial  content.

**Comment by WtfJoke** [comment]
I added some initial content on the learn how to migrate to git/jira link. Basically I just linked to the corresponding github pages.

But I think thats enough for now...

**Comment by WtfJoke** [comment]
Just waiting for the build I guess :stuck_out_tongue:  cause result is not yet viewable

**Comment by reinhapa** [comment]
The bad luck strikes twice. Power outage took down website and build server. Only the web server recovered correctly :-(

Fixed it again...

**Comment by WtfJoke** [comment]
No problem, glad it works now again :)
